server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: Aishu@1101

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true